#!/usr/bin/env bash
# Updates packages lists
sudo apt-get -y update
# Install nginx with zero prompts                                                                                       
sudo apt-get -y install nginx
# modify /var/www recursively
sudo chown -R ubuntu /var/www
# allow traffic
sudo ufw allow "Nginx HTTP"
# Change default content of nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
# implement redirections using sed
patch_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Henry4593 permanent;"
sudo sed -i 's/server_name\s_;/'"$patch_string"'/g' /etc/nginx/sites-enabled/default
# test if running successfully
sudo nginx -t
# service reload
sudo service nginx reload
