#!/usr/bin/env bash
# Customizing a 404-error_page

# Refresh Package List & Install Nginx with no prompts
sudo apt-get update
sudo apt-get install -y nginx

# Create an index.html page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform a "moved permanently redirection" (301)
patch_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$patch_string/" /etc/nginx/sites-enabled/default

# Design a Custom 404 Error Page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
patch_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$patch_string/" /etc/nginx/sites-enabled/default

# Validate Configuration
sudo nginx -t

# Reload Nginx Service
sudo service nginx restart
