#!/usr/bin/env bash
# Craft a Simple 404 Error Experience

# Ensure Up-to-Date Packages (Prereq for Nginx)
sudo apt-get update
sudo apt-get install -y nginx

# Build a Basic Welcome Page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirect Requests to an External Resource (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Henry4593 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Craft a Custom 404 Error Page (French for "This is not a page")
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Add a Custom Header to Identify Server
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Validate Configuration for Errors
sudo nginx -t

# Restart Nginx to Apply Changes
sudo service nginx restart
