#!/usr/bin/env bash
# Install HAProxy load balancer


echo -e "Updating and doing some minor checks...\n"

function install() {
	# Check if package exists
	command -v "$1" &> /dev/null

	#shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

install haproxy #install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup default config
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend aciel-tech-frontend
    bind *:80
    default_backend aciel-tech-backend

backend aciel-tech-backend
    balance roundrobin
    server 308421-web-01 54.237.217.113:80 check
    server 308421-web-02 18.204.7.152:80 check
"

# Write server config
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy auto-start
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "configured - Roundrobin On web-01 & web-02"
# Check and start/restart HAProxy
if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
